### ISSUE TITLE
Missing `purescript-arrays` dependency

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-quickcheck#52]
Pulled from master, and it doesn't build with a fresh `bower install` because `purescript-arrays` is not a listed or transitive dependency.

**Comment by garyb** [comment]
The `master` of core libs all need checking for this - we flipped the dependency of `unfoldable` and `arrays` so that will have broken the graph in some places. I'll be going through them all again when 0.9 is about to be released so will make sure they're all good then. Thanks for the notice though!
